# 设置静态资源访问前缀
# 访问: 当前项目 + static-path-pattern + 静态资源名
#spring:
#  mvc:
#    static-path-pattern: /res/**

# 设置静态资源访问路径    spring.web.resources.static-locations

server:
  port: 8080
  servlet:
    context-path: /mall

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 测试库
spring:
  datasource:
    url: jdbc:mysql://101.133.131.175:3306/testHeartbeat
    username: ecStu
    password: SuperGift#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  elasticsearch:
#    uris: http://localhost:9200
    uris: http://101.133.131.175:9200


# jwt配置
jwt:
  config:
    secret: heartbeat
    ttl: 30000

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql


